
--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Oct 23 2018 13:21
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Select Database: 'db_name'
--
USE db_name
GO

IF DB_NAME() = 'db_name'
    RAISERROR('''db_name'' DATABASE CONTEXT NOW IN USE.',1,1)
ELSE
    RAISERROR('ERROR IN BATCH FILE, ''USE db_name'' FAILED!  KILLING THE SPID NOW.',22,127) WITH LOG
GO

EXECUTE SP_DBOPTION 'db_name' ,'TRUNC. LOG ON CHKPT.' ,'TRUE'
GO

--
-- Permissions for: 'public'
--
GRANT ALL ON DB2 TO public
GO

GRANT ALL ON DB1 TO public
GO

GRANT ALL ON ICollection_PHS TO public
GO

GRANT ALL ON Login TO public
GO

GRANT ALL ON PHS TO public
GO

GRANT ALL ON HS TO public
GO

GRANT ALL ON IMap TO public
GO
