--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Oct 25 2018 16:02
-- Script Generated by Database Design Studio 2.21.3 
--

--
-- Select Database: 'db_name'
--
USE db_name
GO
 
IF DB_NAME() = 'db_name'
    RAISERROR('''db_name'' DATABASE CONTEXT NOW IN USE.',1,1)
ELSE
    RAISERROR('ERROR IN BATCH FILE, ''USE db_name'' FAILED!  KILLING THE SPID NOW.',22,127) WITH LOG
 
GO
EXECUTE SP_DBOPTION 'db_name' ,'TRUNC. LOG ON CHKPT.' ,'TRUE'
GO
--
-- Drop Table    : 'IMap'   
--
DROP TABLE IMap
GO
--
-- Drop Table    : 'HS'   
--
DROP TABLE HS
GO
--
-- Drop Table    : 'PHS'   
--
DROP TABLE PHS
GO
--
-- Drop Table    : 'Login'   
--
DROP TABLE Login
GO
--
-- Drop Table    : 'ICollection_PHS'   
--
DROP TABLE ICollection_PHS
GO
--
-- Drop Table    : 'MAPDB'   
--
DROP TABLE MAPDB
GO
--
-- Drop Table    : 'HSDB'   
--
DROP TABLE HSDB
GO
