--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Oct 25 2018 16:02
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Select Database: 'db_name'
--
USE db_name
GO
 
IF DB_NAME() = 'db_name'
    RAISERROR('''db_name'' DATABASE CONTEXT NOW IN USE.',1,1)
ELSE
    RAISERROR('ERROR IN BATCH FILE, ''USE db_name'' FAILED!  KILLING THE SPID NOW.',22,127) WITH LOG
 
GO
EXECUTE SP_DBOPTION 'db_name' ,'TRUNC. LOG ON CHKPT.' ,'TRUE'
GO

--
-- Create Table    : 'HSDB'   
-- DB2ID           :  
--
CREATE TABLE HSDB (
    DB2ID          INT IDENTITY(1,1) NOT NULL,
CONSTRAINT pk_HSDB PRIMARY KEY CLUSTERED (DB2ID))
GO

--
-- Create Table    : 'MAPDB'   
-- DB1ID           :  
--
CREATE TABLE MAPDB (
    DB1ID          INT IDENTITY(1,1) NOT NULL,
CONSTRAINT pk_MAPDB PRIMARY KEY CLUSTERED (DB1ID))
GO

--
-- Create Table    : 'ICollection_PHS'   
-- ICollectionID   :  
--
CREATE TABLE ICollection_PHS (
    ICollectionID  INT IDENTITY(1,1) NOT NULL,
CONSTRAINT pk_ICollection_PHS PRIMARY KEY CLUSTERED (ICollectionID))
GO

--
-- Create Table    : 'Login'   
-- Name            :  
-- Password        :  
-- DB2ID           :  (references HSDB.DB2ID)
--
CREATE TABLE Login (
    Name           INT IDENTITY(1,1) NOT NULL UNIQUE,
    Password       VARCHAR(50) NOT NULL,
    DB2ID          INT NULL,
CONSTRAINT pk_Login PRIMARY KEY CLUSTERED (Name),
CONSTRAINT fk_Login FOREIGN KEY (DB2ID)
    REFERENCES HSDB (DB2ID)
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'PHS'   
-- Name            :  
-- TotalHS         :  
-- Map             :  
-- PHSValue        :  
-- DB2ID           :  (references HSDB.DB2ID)
--
CREATE TABLE PHS (
    Name           INT IDENTITY(1,1) NOT NULL UNIQUE,
    TotalHS        BIGINT NULL,
    Map            VARCHAR(50) NULL,
    PHSValue       BIGINT NULL,
    DB2ID          INT NULL,
CONSTRAINT pk_PHS PRIMARY KEY CLUSTERED (Name),
CONSTRAINT fk_PHS FOREIGN KEY (DB2ID)
    REFERENCES HSDB (DB2ID)
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'HS'   
-- HSID            :  
-- DB2ID           :  (references HSDB.DB2ID)
-- ICollectionID   :  (references ICollection_PHS.ICollectionID)
--
CREATE TABLE HS (
    HSID           INT IDENTITY(1,1) NOT NULL,
    DB2ID          INT NULL,
    ICollectionID  INT NOT NULL,
CONSTRAINT pk_HS PRIMARY KEY CLUSTERED (HSID),
CONSTRAINT fk_HS FOREIGN KEY (DB2ID)
    REFERENCES HSDB (DB2ID)
    ON UPDATE CASCADE,
CONSTRAINT fk_HS2 FOREIGN KEY (ICollectionID)
    REFERENCES ICollection_PHS (ICollectionID)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'IMap'   
-- IMapID          :  
-- MapName         :  
-- DB2ID           :  (references HSDB.DB2ID)
-- DB1ID           :  (references MAPDB.DB1ID)
--
CREATE TABLE IMap (
    IMapID         INT IDENTITY(1,1) NOT NULL,
    MapName        VARCHAR NOT NULL,
    DB2ID          INT NOT NULL,
    DB1ID          INT NOT NULL,
CONSTRAINT pk_IMap PRIMARY KEY CLUSTERED (IMapID),
CONSTRAINT fk_IMap FOREIGN KEY (DB2ID)
    REFERENCES HSDB (DB2ID)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
CONSTRAINT fk_IMap2 FOREIGN KEY (DB1ID)
    REFERENCES MAPDB (DB1ID)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Permissions for: 'public'
--
GRANT ALL ON HSDB TO public
GO
GRANT ALL ON MAPDB TO public
GO
GRANT ALL ON ICollection_PHS TO public
GO
GRANT ALL ON Login TO public
GO
GRANT ALL ON PHS TO public
GO
GRANT ALL ON HS TO public
GO
GRANT ALL ON IMap TO public
GO

